# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine # Using PostgreSQL 15
    container_name: ashoka_postgres_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Exposes PostgreSQL on your host machine's port 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ashoka_dev_user} # Uses .env variable or default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-replace-with-your-strong-dev-db-password} # Uses .env variable or default
      POSTGRES_DB: ${POSTGRES_DB:-ashoka_dev_db}     # Uses .env variable or default
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ashoka_redis_dev
    ports:
      - "6379:6379" # Exposes Redis on your host machine's port 6379
    volumes:
      - redis_data_dev:/data
    restart: unless-stopped
    # command: redis-server --requirepass ${REDIS_PASSWORD} # Uncomment if you set REDIS_PASSWORD in .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
  redis_data_dev: